# Generated by Django 5.2.2 on 2025-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.DeleteModel(
            name='LocationImage',
        ),
    ]
