# Generated by Django 5.2.2 on 2025-06-11 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_image1_location_image2_location_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
